-- PostgreSQL application consistency kernel. Run in an empty test database.
-- IDs are generated by the application. Identity/profile tables are abbreviated.
CREATE TABLE app_user (id uuid PRIMARY KEY);
CREATE TABLE company (id uuid PRIMARY KEY);
CREATE TABLE candidate_profile (user_id uuid PRIMARY KEY REFERENCES app_user(id));
CREATE TABLE job (
  id uuid PRIMARY KEY,
  company_id uuid NOT NULL REFERENCES company(id),
  state text NOT NULL CHECK (state IN ('Draft','Published','Closed')),
  deadline_at timestamptz,
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  UNIQUE (id, company_id)
);
CREATE TABLE application (
  id uuid PRIMARY KEY,
  candidate_id uuid NOT NULL REFERENCES candidate_profile(user_id),
  job_id uuid NOT NULL,
  company_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'Applied'
    CHECK (status IN ('Applied','Screened','Interview','Offer','Rejected')),
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  snapshot jsonb NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (candidate_id, job_id),
  FOREIGN KEY (job_id, company_id) REFERENCES job(id, company_id)
);
CREATE TABLE application_status_history (
  application_id uuid NOT NULL REFERENCES application(id),
  version bigint NOT NULL,
  from_status text,
  to_status text NOT NULL,
  actor_id uuid NOT NULL REFERENCES app_user(id),
  reason text,
  changed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (application_id, version)
);
CREATE FUNCTION guard_application_transition() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'Applied' OR NEW.version <> 1 THEN
      RAISE EXCEPTION 'application must start Applied at version 1';
    END IF;
  ELSE
    IF (NEW.candidate_id, NEW.job_id, NEW.company_id, NEW.snapshot, NEW.submitted_at)
       IS DISTINCT FROM
       (OLD.candidate_id, OLD.job_id, OLD.company_id, OLD.snapshot, OLD.submitted_at) THEN
      RAISE EXCEPTION 'immutable application identity/snapshot';
    END IF;
    IF NEW.version <> OLD.version + 1 OR NOT (
      (OLD.status = 'Applied' AND NEW.status IN ('Screened','Rejected')) OR
      (OLD.status = 'Screened' AND NEW.status IN ('Interview','Rejected')) OR
      (OLD.status = 'Interview' AND NEW.status IN ('Offer','Rejected'))
    ) THEN
      RAISE EXCEPTION 'invalid application transition/version';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER application_transition BEFORE INSERT OR UPDATE ON application
FOR EACH ROW EXECUTE FUNCTION guard_application_transition();
CREATE FUNCTION forbid_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'status history is append-only';
END $$;
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON application_status_history
FOR EACH ROW EXECUTE FUNCTION forbid_history_mutation();
CREATE TABLE idempotency_record (
  actor_id uuid NOT NULL REFERENCES app_user(id),
  route_scope text NOT NULL,
  key text NOT NULL,
  request_hash text NOT NULL,
  response_code integer,
  response_body jsonb,
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (actor_id, route_scope, key)
);
CREATE TABLE outbox_event (
  event_id uuid PRIMARY KEY,
  aggregate_type text NOT NULL,
  aggregate_id uuid NOT NULL,
  aggregate_version bigint NOT NULL,
  type text NOT NULL,
  schema_version integer NOT NULL DEFAULT 1,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  lease_until timestamptz,
  published_at timestamptz
);
CREATE INDEX application_candidate_page ON application(candidate_id,submitted_at DESC,id DESC);
CREATE INDEX application_pipeline_page ON application(company_id,job_id,status,submitted_at DESC,id DESC);
CREATE INDEX outbox_pending ON outbox_event(created_at) WHERE published_at IS NULL;
-- Domain handler must write history + outbox + receipt in the same transaction.
-- Trigger validates transitions; it does not perform authorization or job-open checks.
-- Runtime DB role: no DELETE on application, no UPDATE/DELETE/TRUNCATE on history.
-- Controlled privacy maintenance uses a separately audited role/migration path.
